<?php
	session_start();
		
	if(!isset($_SESSION['sid'])) //did not login - should not obtain access
	{
		require('fss_logout.php');
		exit;
	}
	else // user logged in - provide them with access
	{
		if(isset($_POST['showHistory'])) //if they have submitted a student
		{
			$selectedSID = $_POST['user']; //store the SID			
		}
		include("head.inc");
?>
<!--
STATISTICS PAGE

Programmed by: JONNY LINTON
ID# 27388489
--> 
<!--****************************   CONTENT SECTION   ***********************************-->
		<div class="content">		
			<h2 class="centerheader2">File Statistics</h2>
			<?php
				if($_SESSION['status'] != 2) // if the user is not a student (prof or TA), allow them to see content
				{
			?>
					<!-- ****************** NON-STUDENT CONTENT ZONE START **************************** -->
					
					<!-- Drop down select menu of students -->
					<h3>Show statistics for a student:</h3>
						<form method="post" action="fss_stats.php">
							<select name="user">
								<option value="none" disabled selected="selected">Select a student</option>
							<?php
								$query = "	SELECT sid, fname, lname
											FROM Users
											WHERE status = 2;";
											
								require('config.php');
								$result = mysql_query($query, $link);
								$rows = mysql_numrows($result);
								for ($i = 0; $i < $rows; $i++)
								{
									$sid = mysql_result($result, $i, 'sid');
									$fname = mysql_result($result, $i, 'fname');
									$lname = mysql_result($result, $i, 'lname');
									echo ("<option value = " . $sid . "> " . $sid . ' - ' . $fname . ' ' . $lname); 

								}
								mysql_close($link);
							?>
							</select><br/><br/>
							<input class ="button" type="submit" name="showHistory" value="Show History" />
						</form>
						<br/>

					<?php
					if(isset($selectedSID)) //if the prof has selected a student
					{
						// display upload, download, deletion history ordered by date/time of event
						
						// <!--****************************   Uploaded Files Display START   *******************************-->
						
						$query = "	SELECT Files.file_name,
										FileVersions.up_date, FileVersions.ass_code, FileVersions.file_size, FileVersions.ip_address,
										Users.fname, Users.lname
									FROM FileVersions, Files, Users
									WHERE FileVersions.up_by = ".$selectedSID."
										AND Files.fid = FileVersions.fid
										AND Users.sid = FileVersions.up_by";
										
						require('config.php'); // Fetch database server info
			
						$result = mysql_query($query, $link); // Store the resulting query from server into variable
						$numOfRows_up = mysql_numrows($result); // Store the number of rows generated by the query
						
						if (!$result) { // Error
							die('Could not get data: '.mysql_error());
							mysql_close($link);
						} 
						else if(mysql_num_rows($result) == 0) { // No files found
							echo('<h3>No uploads!</h3>');
							mysql_close($link);
						}
						else { // Files found
							$fname = mysql_result($result, 0, 'fname');
							$lname = mysql_result($result, 0, 'lname');
							echo("	<h3>" . $fname . " " . $lname . "'s Statistics</h3>
									<fieldset>
										<legend>Uploaded Files</legend>");
							for ($i = 0; $i < $numOfRows_up; $i++) { // Loops for every row generated by query
								
								// Create table and its corresponding headers
								print('	<table class="download">
											<tr>
												<th>File Name</th>
												<th>Upload Date</th>
												<th>Assignment Code</th>
												<th>File Size</th>
												<th>User IP</th>
											</tr>');
								for ($i = 0; $i < $numOfRows_up; $i++) { // Loops for every row generated by query
									print('	<tr>
												<td>');
													$file_name = mysql_result($result, $i, 'file_name');
													print($file_name);
										print(' </td>
												<td>');
													$up_date = mysql_result($result, $i, 'up_date');
													print($up_date);
										print('	</td>
												<td>');
													$ass_code = mysql_result($result, $i, 'ass_code');
													print($ass_code);
										print('	</td>
												<td>');
													$file_size = mysql_result($result, $i, 'file_size')."KB";
													print($file_size);
										print('	</td>
												<td>');
													$ip_address = mysql_result($result, $i, 'ip_address');
													print($ip_address);
										print('	</td>
											</tr>');
								}
								print('	</table></fieldset><br/><br/> ');
								
							}
							mysql_close($link);
						}
						// <!--****************************   Uploaded Files Display END   *******************************-->
						
						
						// <!--****************************   Downloaded Files Display START   *******************************-->
						
						$query = "	SELECT Files.file_name,
										FileVersions.up_date, FileVersions.file_size,
										down.down_date
									FROM FileVersions, Files, down
									WHERE down.fid = Files.fid
										AND FileVersions.up_date = down.up_date
										AND down.down_by = ".$selectedSID.";";
										
						require('config.php'); // Fetch database server info
			
						$result = mysql_query($query, $link); // Store the resulting query from server into variable
						$numOfRows_down = mysql_numrows($result); // Store the number of rows generated by the query
						
						if (!$result) { // Error
						   die('Could not get data: '.mysql_error());
						   mysql_close($link);
						} 
						else if(mysql_num_rows($result) == 0) { // No files found
							mysql_close($link);
							echo('<h3>No downloads!</h3>');
						}
						else { // Files found
							echo("<fieldset> <legend>Downloaded Files</legend> ");
							for ($i = 0; $i < $numOfRows_down; $i++) { // Loops for every row generated by query
								
								// Create table and its corresponding headers
								print('	<table class="download">
											<tr>
												<th>File Name</th>
												<th>Upload Date</th>
												<th>Download Date</th>
												<th>File Size</th>
											</tr>');
								for ($i = 0; $i < $numOfRows_down; $i++) { // Loops for every row generated by query
									print('	<tr>
												<td>');
													$file_name = mysql_result($result, $i, 'file_name');
													print($file_name);
										print(' </td>
												<td>');
													$up_date = mysql_result($result, $i, 'up_date');
													print($up_date);
										print('	</td>
												<td>');
													$down_date = mysql_result($result, $i, 'down_date');
													print($down_date);
										print('	</td>
												<td>');
													$file_size = mysql_result($result, $i, 'file_size')."KB";
													print($file_size);
										print('	</td>
											</tr>');
								}
								print('	</table>');
								
							}
							mysql_close($link);
						}
						
						echo(" </fieldset> " );
						
						// <!--****************************   Downloaded Files Display END   *******************************-->


						// <!--****************************   Deleted Files Display START   *******************************-->
						
						$query = "	SELECT del.file_name, del.ass_code, del.del_date, del.up_date, del.up_by, del.ip_address
									FROM del
									WHERE del.del_by = ".$selectedSID.";";
									
						require('config.php'); // Fetch database server info
			
						$result = mysql_query($query, $link); // Store the resulting query from server into variable
						$numOfRows_del = mysql_numrows($result); // Store the number of rows generated by the query
						
						if (!$result) { // Error
						   die('Could not get data: '.mysql_error());
						   mysql_close($link);
						} 
						else if($numOfRows_del == 0) { // No files found
							mysql_close($link);
							echo('<h3>No deleted files!</h3>');
						}
						else { // Files found
							echo("<fieldset> <legend>Deleted Files</legend> ");
							for ($i = 0; $i < $numOfRows_del; $i++) { // Loops for every row generated by query
								

								// Create table and its corresponding headers
								print('	<table class="download">
											<tr>
												<th>File Name</th>
												<th>Assignment</th>
												<th>Delete Date</th>
												<th>Upload Date</th>
												<th>File Size</th>
												<th>User IP</th>
											</tr>');
								for ($i = 0; $i < $numOfRows_del; $i++) { // Loops for every row generated by query
									print('	<tr>
												<td>');
													$file_name = mysql_result($result, $i, 'file_name');
													print($file_name);
										print(' </td>
												<td>');
													$ass_code = mysql_result($result, $i, 'ass_code');
													print($ass_code);
										print('	</td>
												<td>');
													$del_date = mysql_result($result, $i, 'del_date');
													print($del_date);
										print('	</td>
												<td>');
													$up_date = mysql_result($result, $i, 'up_date');
													print($up_date);
										print('	</td>
												<td>');
													$up_by = mysql_result($result, $i, 'up_by')."KB";
													print($up_by);
										print('	</td>
												<td>');
													$ip_address = mysql_result($result, $i, 'ip_address');
													print($ip_address);
										print('	</td>
											</tr>');
								}
								print('	</table> </fieldset> ');
								
							}
							mysql_close($link);
						}
						
						// <!--****************************   Deleted Files Display END   *******************************-->

						
						//Display number of File Contributions
						echo("<br/><br/>Number of Files Uploaded: ".$numOfRows_up."<br/>Number of Files Downloaded: ".$numOfRows_down."<br/>Number of Files Deleted: ".$numOfRows_del."<br/><br/>");
						
					} // end of if statement
				} // end of non-Student Zone
		
//		<!-- ****************** NON-STUDENT CONTENT ZONE END **************************** -->

				else{ // user trying to access is a student -- deny
						echo("<h2>Access Denied!</h2>");
				}
			?>
		</div>
		
<!--****************************   CONTENT SECTION END   *******************************-->

<?php
	include("footer.inc");
	} // end of else
?>
