<?php
	session_start();
		
	if(!isset($_SESSION['sid']) || $_SESSION['gid'] == 0 && $_SESSION['gid'] != NULL) //did not login - should not obtain access
	{
		require('fss_logout.php');
		exit;
	}
	else // user logged in - provide them with access
	{
		include("head.inc");
?>

<!-- 
DOWNLOAD A FILE

Programmed by: JONNY LINTON & SIMON JACQUES
ID# 27388489 & 27046677
-->

<?php

	// <!--****************************   ARCHIVE SECTION START   ***********************************-->

	if (isset($_POST['archbutton'])) {
		
		// Select file versions information
		$query = "	SELECT FileVersions.path, FileVersions.up_date,
						Files.file_name
					FROM FileVersions, Files
					WHERE Files.fid = FileVersions.fid;";
		
		require('config.php');
		
		$result = mysql_query($query, $link);
		$numOfRows = mysql_num_rows($result);
		$filesMoved = 0;
		
		if (!$result) { // Error
		   die('Could not get data: '.mysql_error());
		} 
		else if ($numOfRows <= 0) {
			echo("<script language=\"javascript\"> alert(\"No files available to archive\") </script>");
		}
		else {			
			for ($i = 0; $i < $numOfRows; $i++) {
				$path = mysql_result($result, $i, 'path'); // Get file path
				$date = mysql_result($result, $i, 'up_date'); // get file upload date
				$name = mysql_result($result, $i, 'file_name'); // Get file name
				$target_path = "archive/" . $date . $name; // Get archived path
				if(rename($path, $target_path)) {
					chmod($target_path, 0664);
					$filesMoved++; // Count the number of files archived
				}
			}
			
			if ($filesMoved == $numOfRows) { // If files archived is equal to files that were stored, then success
				echo("<script language=\"javascript\"> alert(\"Files successfully archived\");</script>");
				
				// Delete all entries from the files table
				$query = "	DELETE FROM Files;";
				mysql_query($query);
				
				// Update current size to 0
				$sql = "UPDATE Groups
						SET current_size = 0;";

				require('config.php');
				mysql_query($sql);
							
				$query = "	DELETE FROM del;";
				
				mysql_query($query);
			}
			else {
				echo("<script language='javascript'> alert('An error occured, not all files could not be archived');</script>");
			}
		}
	}
	
	// <!--****************************   ARCHIVE SECTION END   ***********************************-->
	
?>

<!--****************************   CONTENT SECTION START   ***********************************-->
		<div class="content">
				<?php
					echo("<h2 class='centerheader2'>Manage Files</h2>");
					
					// Store session variables
					$gid = $_SESSION['gid'];
					$status = $_SESSION['status'];

					// Restrict access to students only
					if ($status == 2) {
						
						// Get the class end date
						$query = "	SELECT Info.endDate
									FROM Info;";
									
						require('config.php');
						
						$result = mysql_query($query, $link);
						$endDate = mysql_result($result, 0, 'endDate'); // Store end date
						$date = date("Y-m-d h-i-s");
						
						if ($date >= $endDate) { // Check if today's date is past end date, if yes, don't allow users to see files
							echo("<h3>This class is over. You don't have access to these files anymore</h3>
								</div>");
							include("footer.inc");
							mysql_close($link);
							exit;
						}
						
						echo('<h3>Files available for group ' . $gid . ':</h3>');
						
						// Select all files from group if user is student
						$query = "	SELECT DISTINCT Files.fid, Files.file_name, Files.ass_code, Files.gid,
										Groups.gname
									FROM Files, Users, Groups
									WHERE Files.gid = '" . $gid . "'
										AND Groups.gid = Files.gid
									ORDER BY Files.fid ASC;";
					}
					else { // Accessible to Prof and TAs
						if ($status == 1 || $status == 0) {
							echo('	<h3>Archive all files</h3>
									<form method = "post" action = "fss_download_1.php">
										<button class = "button" value ="null" type = "submit" name = "archbutton">Archive</button>
									</form>');
						}
						echo('	<br/><h3>Files available for all groups:</h3>');
						
						// Select all files from all groups if user is a professor
						$query = "	SELECT DISTINCT Files.fid, Files.file_name, Files.ass_code, Files.gid,
										Groups.gname
									FROM Files, Users, Groups
									WHERE Groups.gid = Files.gid
									ORDER BY Files.fid ASC;";
					}
					
					require('config.php'); // Fetch database server info
					
					$result = mysql_query($query, $link); // Store the resulting query from server into variable
					$numOfRows = mysql_numrows($result); // Store the number of rows generated by the query
					
					if (!$result) { // Error
						mysql_close($link);
						die('Could not get data: '.mysql_error());
					} 
					else if(mysql_numrows($result) == 0) { // No files found
						echo('No files');
					}
					else { // Files found. Create table and its corresponding headers
					
						// Select leader of group to compare to current user
						$query = "	SELECT *
									FROM leads
									WHERE leads.sid = " . $_SESSION['sid'] . ";";
									
						$result2 = mysql_query($query, $link); // Store the resulting query from server into variable
						$numOfRows2 = mysql_numrows($result2); // Get number of rows
						
						// Check if current user is leader 
						if ($numOfRows2 > 0) {
							$leader = true;
						}
						else {
							$leader = false;
						}					
					
						// Print table of all file versions for leaders and latest file for user
						print('	<table class="download">
									<tr>
										<th>ID</th>
										<th>Name</th>
										<th>For</th>
										<th>Group</th>
										<th>Version</th>');
						if ($leader) { // Give leader the option to rollback
							print('		<th>Rollback</th>');
						}
						print ('	</tr>');
						
						for ($i = 0; $i < $numOfRows; $i++) { // Loops for every row generated by query
							print('		<tr>
										<td>'); // Print File ID
											$file_id = mysql_result($result, $i, 'fid');
											print($file_id);
							print(' 	</td>
										<td>'); // Print file name
											$file_name = mysql_result($result, $i, 'file_name');
											print($file_name);
							print('		</td>
										<td>'); // Print assignment code
											$ass_code = mysql_result($result, $i, 'ass_code');
											print($ass_code);
							print('		</td>
										<td>'); // Print group
											$group = mysql_result($result, $i, 'gname');
											print($group);
							// Print button leading to version list
							print('		</td>
										<td>
											<form method ="post" action = "fss_download_1.php">
												<button class="button" name ="file_value" value = "' . $file_id . '" type = "submit">List</button>
											</form>
										</td>');
							if ($leader) { // Print button leading to rollback list
								print('	<td>
											<form method ="post" action = "fss_download_1.php">
												<button class="button" name ="rbkbutton" value = "' . $file_id . '" type = "submit">Options</button>
											</form>
										</td>');
							}					
							print('</tr>');											
						}
						print('	</table>');
					}
					mysql_close($link);					
				 ?>
		</div>
<!--****************************   CONTENT SECTION END   *******************************-->

<?php	
		include("footer.inc");
		
		// <!--****************************   VERSIONS SECTION START   ***********************************-->

		if(isset($_POST['file_value'])) { // Go to download page
			$_SESSION['choice'] = $_POST['file_value'];
			$_SESSION['page'] = 0;
			require_once('fss_download_2.php');
			exit;
		}
		
		// <!--****************************   VERSIONS SECTION END   ***********************************-->
		
		
		// <!--****************************   ROLLBACK SECTION START   ***********************************-->

		if(isset($_POST['rbkbutton'])) { // Go to rollback page
			$_SESSION['choice'] = $_POST['rbkbutton'];
			$_SESSION['page'] = 1;
			require_once('fss_download_2.php');
			exit;
		}
		
		// <!--****************************   ROLLBACK SECTION END   ***********************************-->
		
	} // end of else
?>