<?php
	session_start();
	
	if(!isset($_SESSION['sid'])) //did not login - should not obtain access
	{
		require('fss_logout.php');
		exit;
	}
	else // user logged in - provide them with access
	{
	include("head.inc");
?>
<!-- 
HOME 

Programmed by: JONNY LINTON & SIMON JACQUES
ID# 27388489 & 27046677
--> 

<!--****************************   CONTENT SECTION   ***********************************-->
		<div class="content">
			<h2 class="centerheader2">Welcome to COMP 353 FSS</h2>
			<?php

				// Store session variables
				$sid = $_SESSION['sid'];
				$fname = $_SESSION['fname'];
				$lname = $_SESSION['lname'];
				$gid = $_SESSION['gid'];
				$status = $_SESSION['status'];
				$joinDate = $_SESSION['joinDate'];

				// register the User's status as a string
				switch($status) {
					case 0: $status_string = 'TA'; break;
					case 1: $status_string = 'Professor'; break;
					case 2: $status_string = 'Student'; break;
				}

				echo("<h3>Hello " . $fname . " " . $lname . "!</h3>"); // Display a welcome message


					//QUERY - get the instructor name and the course end date from Info
					$query = " 	SELECT endDate, Users.fname, Users.lname
								FROM Info, Users
								WHERE Info.instruc = Users.sid;";

					require('config.php'); // Fetch database server info

					$result = mysql_query($query, $link);

					if (!$result) // Error
					{ 
					   die('Could not get data: ' . mysql_error());
					   mysql_close($link);
					}
					else 
					{
						$endDate = mysql_result($result, 0, 'endDate');
						$instruc = mysql_result($result, 0, 'fname')." ".mysql_result($result, 0, 'lname') ;

						mysql_close($link);
					}

					// User info fieldset -- Display in a table all of the User information
					echo("<fieldset class='fieldsetBold'><legend>User Information</legend>
						<table >
							<tr>
								<th>User ID</th>
								<th>Status</th>
								<th>Date Joined</th>
								<th>Course End</th>
								<th>Professor</th>
							</tr>
							<tr>
								<td>".$sid."</td>
								<td>".$status_string."</td>
								<td>".$joinDate."</td>
								<td>".$endDate."</td>
								<td>".$instruc."</td>
							</tr>
						</table>");


				if($status == 2) // if user is a student
				{
		// ----------------------- USER HOMEPAGE START ---------------------------
					echo("</fieldset><br/>");

					if($gid > 0) // if the student is in a group - display info
					{ 
						// get group information from database
						$query1 = "	SELECT FileVersions.fid
									FROM FileVersions
									WHERE FileVersions.gid = '" . $gid . "';";

						$query2 = "	SELECT Groups.current_size
									FROM Groups
									WHERE Groups.gid = '" . $gid . "';";

						$query3 = " SELECT maxFiles, endDate
									FROM Info;";

						$query4 = " SELECT Users.fname, Users.lname
									FROM Users, leads
									WHERE leads.gid = ".$gid." AND leads.gid = Users.gid AND leads.sid = Users.sid;";

						require('config.php'); // Fetch database server info

						// Store the resulting queries from server into variables
						$result1 = mysql_query($query1, $link); 
						$result2 = mysql_query($query2, $link);
						$result3 = mysql_query($query3, $link);
						$result4 = mysql_query($query4, $link);

						
						if (!$result1 || !$result2 || !$result3 || !$result4) // if Error
						{ 
						   die('Could not get data: ' . mysql_error());
						   mysql_close($link);
						}
						else 
						{
							$files_avail = mysql_numrows($result1); // Store the number of rows generated by the query
							$space = mysql_result($result2, 0, 'current_size'); // store current size of group's files
							$maxFiles = mysql_result($result3, 0, 'maxFiles'); // store maximum file size, as set by prof.
							if(mysql_numrows($result4) != 0) // if there is a group leader
								$leader = mysql_result($result4, 0, 'fname')." ".mysql_result($result4, 0, 'lname'); // get the leader for this group.
							else
								$leader = "n/a";
							mysql_close($link);
						}

						// Group Info Fieldset -- Display in a table all of the group's information
						echo("<fieldset class='fieldsetBold'><legend>Group Information</legend>
				
						<table >
							<tr>
								<th>Group ID</th>
								<th>Files Available</th>
								<th>Size of Group Files (KB)</th>
								<th>Group Leader</th>
							</tr>
							<tr>
								<td>".$gid."</td>
								<td>".$files_avail."</td>
								<td>".$space."/".$maxFiles."</td>
								<td>".$leader."</td>
							</tr>
						</table>
						<h4>Group Members:</h4>
						<table>
							<tr>
								<th>Student ID</th>
								<th>Name</th>
							</tr> ");

						//QUERY -- get the information of all members of this User's group
						$query = "SELECT sid, fname, lname FROM Users WHERE status = 2 AND gid = ".$gid." ORDER BY sid;";

						require('config.php'); // Fetch database server info

						$result = mysql_query($query, $link); // store result
						$rows = mysql_numrows($result); // get the number of rows resulting from the query

						if (!$result) // If error
						{ 
						   die('Could not get data: ' . mysql_error());
						   mysql_close($link);
						}
						else
						{
							for ($i = 0; $i < $rows; $i++) // for every row of results - print a row
							{
								echo("<tr>");
									$sid = mysql_result($result, $i, 'sid');
									echo("<td>" . $sid . "</td>");
									$full_name = mysql_result($result, $i, 'fname') . " " . mysql_result($result, $i, 'lname');
									echo("<td>" . $full_name . "</td>");
								echo("</tr>");
							}
							mysql_close($link);
							echo("</table>");
						}

						
						//QUERY -- get the file name and assignment code for this group from Files table
						$query5 = " SELECT Files.file_name, Files.ass_code
									FROM Files
									WHERE Files.gid = ".$gid.";";

						require('config.php'); // Fetch database server info
						$result5 = mysql_query($query5, $link); // store result

						if (!$result5) // if Error
						{ 
						   die('Could not get data: ' . mysql_error());
						   mysql_close($link);
						}
						else
						{
							$rows = mysql_numrows($result5); // store number of resulting rows
						}
						
						//Create a table for the Group's Files
						echo("
							<h4>Available Files for Group ".$gid.":</h4>
							<table>
							<tr>
								<th>File Name</th>
								<th>Assignment</th>
							</tr>");
							for ($i = 0; $i < $rows; $i++) // for each row, print a row in HTML
							{
								echo("<tr>");
									$file_name = mysql_result($result5, $i, 'file_name');
									echo("<td>" . $file_name . "</td>");
									$ass_code = mysql_result($result5, $i, 'ass_code');
									echo("<td>" . $ass_code . "</td>");
								echo("</tr>");
							}
							echo("</table>
							
							</fieldset><br/><br/>");


					}
					else // student is not in a group
					{
						echo("<fieldset><legend>Group Information</legend>
							<h4>You are not in a group!</h4><br/>
							</fieldset>");
					}

		// ----------------------- USER HOMEPAGE END -----------------------------
				} // if($status == 2) END

				else if ($status == 1 || $status == 0) // user is a professor or a TA
				{
		// ----------------------- PROF HOMEPAGE START ---------------------------
					echo("<h4> All Users: </h4>
						<table>");

					//QUERY -- get the info for all Users
					$query = "SELECT sid, fname, lname FROM Users ORDER BY sid;";

					require('config.php'); // Fetch database server info

					$result = mysql_query($query, $link); // Store the result
					$rows = mysql_numrows($result); // store the resulting rows

					if (!$result) // If Error
					{ 
					   die('Could not get data: ' . mysql_error());
					   mysql_close($link);
					}
					else
					{
						// print a table with all of the Users in the system
						echo("<tr>
								<th>User ID</th>
								<th>Name</th>
							</tr> ");
						
						for ($i = 0; $i < $rows; $i++) // for each row of result, print a row in HTML
						{
							echo("<tr>");
								$sid = mysql_result($result, $i, 'sid');
								echo("<td>" . $sid . "</td>");
								$full_name = mysql_result($result, $i, 'fname') . " " . mysql_result($result, $i, 'lname');
								echo("<td>" . $full_name . "</td>");
							echo("</tr>");
						}
						mysql_close($link);
						echo("</table>");
					}

					echo("</fieldset><br/><fieldset class='fieldsetBold'><legend> Group Information </legend>");

					// QUERIES -- get all group info, File info, and the max file size (as set by prof)
					$query6 = " SELECT * FROM Groups;";

					$query5 = " SELECT Files.file_name, Files.ass_code, Files.gid
								FROM Files
								ORDER BY gid;";
					$query3 = " SELECT maxFiles
								FROM Info;";

					require('config.php'); // Fetch database server info

					// Store the results
					$result5 = mysql_query($query5, $link);
					$result6 = mysql_query($query6, $link);
					$result3 = mysql_query($query3, $link);

					if (!$result5 || !$result6 || !$result3) // if Error
					{ 
					   die('Could not get data: ' . mysql_error());
					   mysql_close($link);
					}
					else
					{
						$rows = mysql_numrows($result5);
						$rows2 = mysql_numrows($result6);
						$maxFiles = mysql_result($result3, 0, 'maxFiles'); 
					}
					
					// print a table with basic group File info
					echo("
						<h4>Available Files:</h4>
						<table>
						<tr>
							<th>Group ID</th>
							<th>File Name</th>
							<th>Assignment</th>
						</tr>");
					for ($i = 0; $i < $rows; $i++) // for each resulting row, print a row in HTML
					{
						echo("<tr>");
							$gid = mysql_result($result5, $i, 'gid');
							echo("<td>" . $gid . "</td>");
							$file_name = mysql_result($result5, $i, 'file_name');
							echo("<td>" . $file_name . "</td>");
							$ass_code = mysql_result($result5, $i, 'ass_code');
							echo("<td>" . $ass_code . "</td>");
						echo("</tr>");
					}
					echo("</table>");

					// print basic group information
					echo("
						<h4>Groups:</h4>
						<table>
						<tr>
							<th>Group ID</th>
							<th>Group Name</th>
							<th>Total File Size (KB)</th>
						</tr>");
					for ($i = 1; $i < $rows2; $i++) // for each resulting row, print a row in HTML
					{
						echo("<tr>");
							$gid = mysql_result($result6, $i, 'gid');
							echo("<td>" . $gid . "</td>");
							$gname = mysql_result($result6, $i, 'gname');
							echo("<td>" . $gname . "</td>");
							$file_size = mysql_result($result6, $i, 'current_size');
							echo("<td>" . $file_size . "/" . $maxFiles . "</td>");
						echo("</tr>");
					}
					echo("</table>");

					mysql_close($link);
					echo("</fieldset><br/><br/>");

		// ----------------------- PROF HOMEPAGE END -----------------------------
				}
				else // status is not set
				{
					echo("<h4>An error occurred! You do not have a status!</h4>");
				}
			 ?>

		</div>
<!--****************************   CONTENT SECTION END   *******************************-->
<?php
	include("footer.inc");
	} // end of else (user logged in)
?>
